### ISSUE TITLE
Automatic loading

### ISSUE THREAD

**Issue by includebrasil** [Novicell/novicell-overlay#2]
I can not make the popup load automatically. It's possible?

**Comment by Dan9boi** [comment]
Hi @includebrasil 

This project is not completely done yet. That's why the documentation is lacking.
May i refer to the demo as the best documentation for now: https://github.com/Novicell/novicell-overlay/blob/master/demo/index.html

When you want to trigger the overlay, you just need to run the `novicell.overlay.create` method, like this:
```javascript
document.addEventListener("DOMContentLoaded", function () {
  novicell.overlay.create({
    'selector': '#some-id'
  });
});
```
